# full_panorama is a full configuration file using jinja
# this is a complete Panorama and reference device-group and template stack configuration
# this is based on a 'shared model' with all device-group elements in Shared
# this is based on a 'shared model' with all template elements in the 'iron-skillet' template

# snippet folder name
name: full_panorama
# label used for menu selection
label: v8.1 Iron-Skillet for Panorama (Shared Values)
description: Iron-Skillet baseline configuration for Panorama with device-group and stack specific values
# type of device configuration
type: panorama
extends:

# grouping of like snippets for dynamic menu creation in pan-cnc
labels:
  service_type: iron_skillet_full
  template_category: panorama_full

# variables used in the configuration templates
# type_hint defines the form field type in pan-cnc
variables:
  - name: PANORAMA_TYPE
    description: Panorama management IP type
    default: static
    type_hint: dropdown
    dd_list:
      - key: static
        value: static
      - key: cloud dhcp
        value: cloud
  - name: PANORAMA_NAME
    description: Panorama hostname
    default: panorama01
    type_hint: text
  - name: PANORAMA_IP
    description: Panorama IP
    default: 192.168.55.7
    type_hint: ip_address
  - name: PANORAMA_MASK
    description: Panorama netmask
    default: 255.255.255.0
    type_hint: ip_address
  - name: PANORAMA_DG
    description: Panorama default gateway
    default: 192.168.55.2
    type_hint: ip_address
  - name: CONFIG_EXPORT_IP
    description: IP address for scheduled config exports
    default: 192.0.2.3
    type_hint: ip_address
  - name: STACK
    description: Template stack name for Panorama
    default: sample_stack
    type_hint: text
  - name: DEVICE_GROUP
    description: Device-group name for Panorama
    default: sample_devicegroup
    type_hint: text
  - name: FW_NAME
    description: Device Name for NGFW
    default: sample
    type_hint: text
  - name: MGMT_TYPE
    description: firewall management IP type
    default: dhcp-client
    type_hint: dropdown
    dd_list:
      - key: dhcp-client
        value: dhcp-client
      - key: static
        value: static
  - name: MGMT_IP
    description: NGFW management IP
    default: 192.0.2.6
    type_hint: ip_address
  - name: MGMT_MASK
    description: NGFW management netmask
    type_hint: ip_address
    default: 255.255.255.0
  - name: MGMT_DG
    description: NGFW management default gateway
    default: 192.0.2.7
    type_hint: ip_address
  - name: NTP_1
    description: Network Time Protocol Server
    default: 0.pool.ntp.org
    type_hint: ip_address
  - name: NTP_2
    description: Network Time Protocol Server 2
    default: 1.pool.ntp.org
    type_hint: ip_address
  - name: ADMINISTRATOR_USERNAME
    description: admin username
    default: admin
    type_hint: text
  - name: ADMINISTRATOR_PASSWORD
    description: admin password
    default: admin
    type_hint: password
  - name: DNS_1
    description: primary dns server
    default: 8.8.8.8
    type_hint: text
  - name: DNS_2
    description: secondary dns server
    default: 8.8.4.4
    type_hint: text
  - name: SINKHOLE_IPV4
    description: sinkhole address IPv4
    default: 72.5.65.111
    type_hint: ip_address
  - name: SINKHOLE_IPV6
    description: sinkhole address IPv6
    default: 2600:5200::1
    type_hint: ip_address
  - name: INTERNET_ZONE
    description: untrust zone to filter out in reports
    default: untrust
    type_hint: text
  - name: EMAIL_PROFILE_GATEWAY
    description: email gateway address for critical alerts
    default: 192.0.2.1
    type_hint: ip_address
  - name: EMAIL_PROFILE_FROM
    description: from address in email alerts
    default: sentfrom@yourdomain.com
    type_hint: text
  - name: EMAIL_PROFILE_TO
    description: to address in email alerts
    default: sendto@yourdomain.com
    type_hint: text
  - name: SYSLOG_SERVER
    description: syslog server ip address
    default: 192.0.2.2
    type_hint: ip_address

snippets:
  - name: panorama-full
    file: iron_skillet_panorama_full.xml

