# snippets_dgstack_shared is used to add device-groups and template stacks only
# this is a partial configuration for device-group and template stack only
# this is based on a 'shared model' with all device-group elements in Shared
# this is based on a 'shared model' with all template elements in the 'iron-skillet' template

# snippet folder name
name: skillet_panorama_dgstack_shared_v90
# label used for menu selection
label: v9.0 Iron-Skillet for Panorama with Device-Group and Stack only (Shared Values)
description: Iron Skillet device-group and template stack config for Panorama
dependency: snippets
# type of device configuration
type: panorama
extends:

# grouping of like snippets for dynamic menu creation in pan-cnc
labels:
  service_type: iron_skillet
  collection: IronSKillet

# variables used in the configuration templates
# type_hint defines the form field type in pan-cnc
variables:
  - name: STACK
    description: Template stack name for Panorama
    default: sample_stack
    type_hint: text
  - name: DEVICE_GROUP
    description: Device-group name for Panorama
    default: sample_devicegroup
    type_hint: text
  - name: FW_NAME
    description: Device Name for NGFW
    default: sample
    type_hint: text
  - name: MGMT_TYPE
    description: firewall management IP type
    default: dhcp-client
    type_hint: dropdown
    dd_list:
      - key: dhcp-client
        value: dhcp-client
      - key: static
        value: static
  - name: MGMT_IP
    description: NGFW management IP
    default: 192.0.2.6
    type_hint: ip_address
  - name: MGMT_MASK
    description: NGFW management netmask
    type_hint: ip_address
    default: 255.255.255.0
  - name: MGMT_DG
    description: NGFW management default gateway
    default: 192.0.2.7
    type_hint: ip_address
  - name: ADMINISTRATOR_USERNAME
    description: admin username
    default: admin
    type_hint: text
  - name: ADMINISTRATOR_PASSWORD
    description: admin password
    default: admin
    type_hint: text


# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: stack
    xpath: /config/devices/entry[@name='localhost.localdomain']/template-stack
    file: ../snippets/template_stack.xml
  - name: device_system_local
    xpath: /config/devices/entry[@name='localhost.localdomain']/template-stack/entry[@name='{{ STACK }}']/config/devices/entry[@name='localhost.localdomain']/deviceconfig/system
    file: ../snippets/device_system_local.xml
  - name: devicegroup
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group
    file: ../snippets/device_group.xml
  - name: reports
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/reports
    file: ../snippets/reports_simple.xml
  - name: report_group_simple
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/report-group
    file: ../snippets/report_group_simple.xml
  - name: email_scheduler
    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE_GROUP }}']/email-scheduler
    file: ../snippets/email_scheduler_simple.xml